export const ADD_MESSAGES = "ADD_MESSAGES";
export const SET_DEVICE_SIZE = "SET_DEVICE_SIZE";
export const SET_CURRENT_REALTOR = "SET_CURRENT_REALTOR";
export const SET_MESSAGES = "SET_MESSAGES";
export const SET_REALTORS = "SET_REALTORS";
export const SET_SELECTED_MESSAGE = "SET_SELECTED_MESSAGE";
export const UPDATE_ONE_MESSAGE = "UPDATE_ONE_MESSAGE";
